#!/usr/bin/env node
/**
 * sop-generate fallback script — native Playwright version
 *
 * Use only when playwright-mcp isn't configured (`claude mcp list | grep -i playwright`
 * comes back empty). Three stages: login → traverse → screenshot. The script only
 * produces screenshot files + a per-page accessibility-summary JSON — it never writes
 * copy. Copy is generated by Claude reading the summary JSON; feeding a full-page
 * screenshot to the model is forbidden.
 *
 * Usage (cwd is usually the target project's root — always call this script with an
 * absolute path):
 *   SOP_USER='<test account username>' SOP_PASS='<test account password>' \
 *   node <this skill's base directory>/scripts/crawl.mjs \
 *     --url https://internal-app.example \
 *     --out docs/sop-images \
 *     [--login-selector-user '#username'] [--login-selector-pass '#password'] \
 *     [--login-selector-submit 'button[type=submit]'] \
 *     [--nav-selector 'nav a'] \
 *     [--actions actions.json]
 *
 * How credentials are passed in (hard rule, no exceptions):
 *   Prefer reading from the SOP_USER / SOP_PASS environment variables. --user/--pass
 *   command-line arguments are still parsed for compatibility, but **not recommended**
 *   — argv lands in shell history, is visible in the `ps aux` process listing, and in
 *   the session transcript/tool-call record. That exposure exists even though the
 *   script itself never writes credentials to any output file. The caller (Claude)
 *   must prefer the environment-variable invocation.
 *
 * Dependency: playwright (npm install playwright, or an existing global install).
 * If the dependency is missing, the script prints the install command and exits —
 * it never installs silently.
 *
 * Hard rules:
 *   - Credentials are used only for this run's login action; the script never writes
 *     them into any output file (screenshots/summary JSON/logs). The caller (Claude)
 *     must likewise never write credentials into a produced document.
 *   - Traversal never follows logout/sign-out links, external links, or non-http(s)
 *     protocol links, to avoid silently producing a batch of "error screenshots"
 *     after the session gets invalidated (see isSkippableLink / isLoginRoute below).
 *
 * --actions <json file> (optional, for the "before/after pair for key operations"
 * requirement in Step 3):
 *   [
 *     { "url": "https://.../export", "click": "button#export",
 *       "before": "export-before", "after": "export-after",
 *       "captureDownload": true }
 *   ]
 *   Per entry: navigate to url (current page if omitted) → wait for the app to be
 *   ready (see "SPA readiness wait" below) → take the before screenshot →
 *   click the selector → wait for network idle → take the after screenshot.
 *   Output goes to <out>/_actions/<name>-before.png / -after.png.
 *   This only covers simple side-effect operations like "click a button"; more
 *   complex multi-step forms should still be captured manually via MCP.
 *   Optional captureBusyState:true — skips the readiness wait after the click and
 *   captures the transient busy state right after clicking (e.g. "Exporting…" copy);
 *   by default (unset), the script waits for readiness after the click (see "SPA
 *   readiness wait" below) before taking the after screenshot, so it captures the
 *   state once the click-triggered data has settled, not a half-finished state.
 *   Optional captureDownload:true — when the click triggers a browser download,
 *   simultaneously capture that download event, save the file to
 *   <out>/_actions/<name>-download.<ext>, and record {name, suggestedFilename,
 *   sizeBytes} to <out>/_actions/_downloads.json, giving Claude evidence that "the
 *   operation actually had an effect" (filename/byte count) without screenshotting
 *   the entire business dataset. The downloaded file itself carries no credentials,
 *   but may contain real business data — decide for yourself whether to check it in
 *   before writing it into the manual.
 *
 * SPA readiness wait (important, learned the hard way): hash-routed pages (e.g.
 * #/reports/xxx) don't fire native browser navigation events on in-page transitions,
 * so domcontentloaded/networkidle pass almost instantly after goto — but the page's
 * data isn't fetched by the frontend effect until after the route switch, later than
 * those two events. Trusting networkidle alone catches a half-finished "loading…"
 * page (in practice, every hash-internal navigation screenshot after the first real
 * full-page load hits this trap). So after every goto, this script additionally
 * polls until the page's own "loading" copy disappears (see waitForAppReady) before
 * taking the screenshot.
 */

import fs from "node:fs";
import path from "node:path";

const LOGOUT_KEYWORDS = /logout|log-out|signout|sign-out|登出|注销|退出登录|退出系统/i;
const LOGIN_ROUTE_PATTERN = /\/(login|signin|sign-in|auth|sso)(\/|$|\?|#)/i;

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith("--")) {
        args[key] = next;
        i++;
      } else {
        args[key] = true;
      }
    }
  }
  return args;
}

function slugify(s) {
  return (
    s
      .toLowerCase()
      .replace(/^https?:\/\//, "")
      .replace(/[^a-z0-9一-龥]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "page"
  );
}

/**
 * Decides whether an href collected from the nav bar should be skipped during
 * traversal:
 *   - empty-protocol anchors (#), mailto:, javascript:, etc. — not real pages
 *   - non-http/https protocols
 *   - cross-origin external links (traversal is scoped to the target system itself)
 *   - logout/sign-out links (hitting one invalidates the whole session)
 * Returns { skip: boolean, reason?: string }
 */
function isSkippableLink(href, linkText, baseOrigin) {
  if (!href || href === "#") {
    return { skip: true, reason: "anchor/empty link" };
  }
  if (href.startsWith("#")) {
    // Hash-routed SPA (e.g. #/reports/tier): a real page, not an anchor; a plain
    // #section anchor (no slash) is still skipped
    if (!href.startsWith("#/")) return { skip: true, reason: "in-page anchor" };
    return { skip: false };
  }
  if (/^(mailto|javascript|tel):/i.test(href)) {
    return { skip: true, reason: "non-page protocol" };
  }
  let resolved;
  try {
    resolved = new URL(href, baseOrigin);
  } catch {
    return { skip: true, reason: "unparseable URL" };
  }
  if (resolved.protocol !== "http:" && resolved.protocol !== "https:") {
    return { skip: true, reason: `protocol not in allowlist: ${resolved.protocol}` };
  }
  if (resolved.origin !== baseOrigin) {
    return { skip: true, reason: `cross-origin external link: ${resolved.origin}` };
  }
  const haystack = `${href} ${linkText || ""}`;
  if (LOGOUT_KEYWORDS.test(haystack)) {
    return { skip: true, reason: "looks like a logout/sign-out link" };
  }
  return { skip: false };
}

function isLoginRoute(urlStr) {
  try {
    const u = new URL(urlStr);
    return LOGIN_ROUTE_PATTERN.test(u.pathname + u.search + u.hash);
  } catch {
    return false;
  }
}

/**
 * "Readiness wait" for hash-routed SPAs: after goto, networkidle passes almost
 * immediately (a client-side route transition doesn't count as a native browser
 * navigation), but the page's data is only fetched by the frontend effect after the
 * route switch. Polls until the "loading" copy disappears, and doesn't throw on
 * timeout (not every page has this copy, or the page may genuinely be reading a slow
 * query) — the caller judges from the screenshot; the script's job is just to wait
 * properly, not to fail the run over it.
 */
async function waitForAppReady(page, { timeoutMs = 15000, loadingTexts = ["Loading", "加载中"] } = {}) {
  // A brief nap before polling starts: after a hash-internal navigation, the new
  // route's "loading" copy often takes a beat to render — skip this nap and
  // readiness gets mistakenly declared before the copy even shows up, and all you
  // get is the fixed 400ms wait at the end of this function.
  await page.waitForTimeout(300);
  try {
    await page.waitForFunction(
      (texts) => !texts.some((t) => document.body.innerText.includes(t)),
      loadingTexts,
      { timeout: timeoutMs },
    );
  } catch {
    // Timeout: proceed anyway. The screenshot still gets taken, possibly of an
    // unfinished state — left for manual review.
  }
  // There's usually a bit more render time between data arriving and charts/tables
  // finishing their draw — leave some margin.
  await page.waitForTimeout(400);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.url || typeof args.url !== "string") {
    console.error(
      "Usage: SOP_USER=<username> SOP_PASS=<password> node crawl.mjs --url <deployed URL> --out <screenshot output dir>",
    );
    process.exit(1);
  }

  let chromium;
  try {
    ({ chromium } = await import("playwright"));
  } catch (e) {
    console.error(
      "[sop-generate] playwright not found, please run: npm install playwright && npx playwright install chromium",
    );
    process.exit(1);
  }

  const outDir = path.resolve(args.out || "docs/sop-images");
  fs.mkdirSync(outDir, { recursive: true });

  const baseOrigin = new URL(args.url).origin;

  // Credentials: prefer environment variables; --user/--pass compatible but not
  // recommended (see file header comment)
  const user = process.env.SOP_USER || args.user;
  const pass = process.env.SOP_PASS || args.pass;
  if (args.user || args.pass) {
    console.warn(
      "[sop-generate] Detected --user/--pass command-line arguments: not recommended, credentials land in shell history and the process list. " +
        "Please invoke this script with the SOP_USER/SOP_PASS environment variables instead.",
    );
  }

  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  console.log(`[sop-generate] opening ${args.url}`);
  await page.goto(args.url, { waitUntil: "domcontentloaded" });

  // --- Login stage (optional, runs when credentials are supplied) ---
  let loggedIn = false;
  if (user && pass) {
    const userSel =
      args["login-selector-user"] || 'input[name="username"], input[type="email"], #username, input[type="text"]';
    const passSel =
      args["login-selector-pass"] || 'input[name="password"], input[type="password"], #password';
    const submitSel = args["login-selector-submit"] || 'button[type="submit"], input[type="submit"]';
    try {
      await page.fill(userSel, user);
      await page.fill(passSel, pass);
      await page.click(submitSel);
      await page.waitForLoadState("networkidle").catch(() => {});
      loggedIn = !isLoginRoute(page.url());
      if (loggedIn) {
        console.log("[sop-generate] login action executed (credentials are never written to any output file)");
      } else {
        console.warn(
          "[sop-generate] still on a login-state route after submitting login; login may have failed. Continuing traversal, but the page is likely a login page — check whether --login-selector-* matches.",
        );
      }
    } catch (e) {
      console.warn(
        `[sop-generate] login selector didn't match (${e.message}). Specify the actual selectors with --login-selector-*, or switch to playwright-mcp for a manual login before traversing.`,
      );
    }
  } else {
    console.log(
      "[sop-generate] no credentials supplied (SOP_USER/SOP_PASS), skipping the login stage (fine for pages that don't require login, or when already logged in manually via MCP)",
    );
  }

  // --- Traversal stage: collect page links from the nav structure, filter out
  //     logout/external/illegal-protocol links ---
  const navSel = args["nav-selector"] || "nav a, header a, aside a";
  const rawLinks = await page.$$eval(navSel, (els) =>
    els.map((el) => ({ href: el.getAttribute("href"), text: (el.textContent || "").trim() })),
  );

  const seen = new Set();
  const links = [];
  const skipped = [];
  for (const { href, text } of rawLinks) {
    if (!href || seen.has(href)) continue;
    seen.add(href);
    const verdict = isSkippableLink(href, text, baseOrigin);
    if (verdict.skip) {
      skipped.push(`${href} (${verdict.reason})`);
    } else {
      links.push(href);
    }
  }
  console.log(`[sop-generate] found ${links.length} traversable links from the nav: ${links.join(", ")}`);
  if (skipped.length > 0) {
    console.log(`[sop-generate] filtered out ${skipped.length} links:\n  ${skipped.join("\n  ")}`);
  }

  const summary = [];
  // The landing page itself must be in the traversal set (deduped, placed first),
  // or it gets skipped whenever the nav has other links.
  // Anchor on the normalized href (not the raw args.url): URL fills in things like a
  // trailing slash, and if the two don't match, the landing page gets slugified as
  // "app-example" instead of "home" (see the slug check below).
  const landingHref = new URL(args.url).href;
  const pagesToVisit = [...new Set([landingHref, ...links])];

  for (const link of pagesToVisit) {
    const target = link.startsWith("http") ? link : new URL(link, args.url).toString();
    const slug = slugify(link === landingHref ? "home" : link);
    const pageDir = path.join(outDir, slug);
    fs.mkdirSync(pageDir, { recursive: true });

    try {
      await page.goto(target, { waitUntil: "domcontentloaded" });
      await page.waitForLoadState("networkidle").catch(() => {});
      await waitForAppReady(page);

      // Session validity check: if we got bounced back to the login page mid-run,
      // the session is invalidated and every screenshot from here on is just the
      // login page — abort immediately.
      if (user && pass && loggedIn && isLoginRoute(page.url())) {
        console.error(
          `[sop-generate] landed back on a login-state route (${page.url()}) after visiting ${target}; the session may have expired. Aborting traversal — pages collected so far are in _index.json.`,
        );
        break;
      }

      // Save the screenshot
      const screenshotPath = path.join(pageDir, "full.png");
      await page.screenshot({ path: screenshotPath, fullPage: true });

      // Accessibility summary (no full-page screenshot content — for Claude to
      // write copy from)
      // page.accessibility was removed in newer Playwright; ariaSnapshot (v1.44+)
      // is the official replacement
      const snapshot = await page.locator("body").ariaSnapshot();
      const interactive = await page.$$eval(
        "a, button, input, select, textarea, [role=button]",
        (els) =>
          els.slice(0, 200).map((el) => ({
            tag: el.tagName.toLowerCase(),
            role: el.getAttribute("role") || undefined,
            text: (el.textContent || el.getAttribute("placeholder") || el.getAttribute("aria-label") || "")
              .trim()
              .slice(0, 60),
          })),
      );

      const pageSummary = {
        url: target,
        slug,
        title: await page.title(),
        screenshot: path.relative(process.cwd(), screenshotPath),
        interactiveElements: interactive,
      };
      fs.writeFileSync(
        path.join(pageDir, "summary.json"),
        JSON.stringify(pageSummary, null, 2),
        "utf-8",
      );
      summary.push(pageSummary);
      console.log(`[sop-generate] collected: ${target} -> ${pageDir}`);
    } catch (e) {
      console.warn(`[sop-generate] page collection failed, skipping: ${target} (${e.message})`);
    }
  }

  fs.writeFileSync(path.join(outDir, "_index.json"), JSON.stringify(summary, null, 2), "utf-8");
  console.log(`[sop-generate] done, page list at ${path.join(outDir, "_index.json")}`);

  // --- Optional stage: before/after screenshots for key operations (--actions <json file>) ---
  if (args.actions) {
    const actionsPath = path.resolve(String(args.actions));
    let actionList = [];
    try {
      actionList = JSON.parse(fs.readFileSync(actionsPath, "utf-8"));
    } catch (e) {
      console.warn(`[sop-generate] failed to read --actions file, skipping this stage: ${e.message}`);
      actionList = [];
    }
    if (actionList.length > 0) {
      const actionsDir = path.join(outDir, "_actions");
      fs.mkdirSync(actionsDir, { recursive: true });
      const downloads = [];
      for (const action of actionList) {
        const name = action.name || slugify(action.click || action.url || "action");
        try {
          if (action.url) {
            await page.goto(action.url, { waitUntil: "domcontentloaded" });
            await page.waitForLoadState("networkidle").catch(() => {});
            await waitForAppReady(page);
          }
          if (user && pass && isLoginRoute(page.url())) {
            console.warn(`[sop-generate] action ${name}'s pre-navigation landed back on the login page, skipping this action.`);
            continue;
          }
          const beforePath = path.join(actionsDir, `${name}-${action.before || "before"}.png`);
          await page.screenshot({ path: beforePath, fullPage: true });
          if (action.click) {
            if (action.captureDownload) {
              const [download] = await Promise.all([
                page.waitForEvent("download"),
                page.click(action.click),
              ]);
              const suggested = download.suggestedFilename();
              const ext = path.extname(suggested) || "";
              const downloadPath = path.join(actionsDir, `${name}-download${ext}`);
              await download.saveAs(downloadPath);
              const sizeBytes = fs.statSync(downloadPath).size;
              downloads.push({ name, suggestedFilename: suggested, sizeBytes, savedTo: path.relative(process.cwd(), downloadPath) });
              console.log(`[sop-generate] captured download: ${name} -> ${suggested} (${sizeBytes} bytes)`);
            } else {
              await page.click(action.click);
            }
            await page.waitForLoadState("networkidle").catch(() => {});
            // The click itself may also trigger new async data requests (e.g.
            // switching a report's basis re-pulls data), which likewise briefly
            // shows a "loading…" half-finished state first — unless the caller
            // explicitly wants to capture that fleeting busy state (see
            // captureBusyState), wait for readiness once more by default, to
            // capture the state that actually settled after the click.
            if (!action.captureBusyState) await waitForAppReady(page);
          }
          const afterPath = path.join(actionsDir, `${name}-${action.after || "after"}.png`);
          await page.screenshot({ path: afterPath, fullPage: true });
          console.log(`[sop-generate] action screenshots done: ${name} -> ${beforePath}, ${afterPath}`);
        } catch (e) {
          console.warn(`[sop-generate] action ${name} failed, skipping: ${e.message}`);
        }
      }
      if (downloads.length > 0) {
        fs.writeFileSync(
          path.join(actionsDir, "_downloads.json"),
          JSON.stringify(downloads, null, 2),
          "utf-8",
        );
      }
    }
  }

  await browser.close();
}

main().catch((e) => {
  console.error("[sop-generate] script execution failed:", e);
  process.exit(1);
});
